version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - ${DOCKER_PORT}:8000
